LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('superadmin/', include('superadmin.urls')),
    path('school/', include('school.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('accounts/', include('account.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
]

LMS/student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('signup_info/', views.signup_info, name='signup_info'),
    path('dash/', views.dash, name='dash'),
    path('class_select/', views.class_select, name='class_select'),
    path('class_signup/<int:class_id>/', views.class_signup, name='class_signup'),
    path('my_class/', views.my_class, name='my_class'),
    path('take_class/<int:course_id>/<int:enroll_id>/', views.take_class, name='take_class'),
    path('take_lecture/<int:lecture_id>/<int:enroll_id>/', views.take_lecture, name='take_lecture'),
    path('take_lecture_code/<int:lecture_id>/<int:enroll_id>/', views.take_lecture_code, name='take_lecture_code'),
    path('take_quiz/<int:quiz_id>/<int:enroll_id>/', views.take_quiz, name='take_quiz'),
    path('take_final_quiz/<int:final_quiz_id>/<int:enroll_id>/', views.take_final_quiz, name='take_final_quiz'),
    path('my_quiz/', views.my_quiz, name='my_quiz'),
    path('setting_profile/', views.setting_profile, name='setting_profile'),
    path('setting_photo/', views.setting_photo, name='setting_photo'),
    path('setting_account/', views.setting_account, name='setting_account'),
]

LMS/student/models.py
from django.db import models
from account.models import User
from school.models import School


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

LMS/student/views.py
from django.shortcuts import render, redirect
from .models import *
from school.models import *
from teacher.models import *
from superadmin.models import *
from account.forms import UserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.hashers import check_password


def signup_info(request):
    if request.method == 'POST':
        school_id = request.POST.get("select_school", None)
        school = School.objects.get(id=school_id)

        new_student = Student.objects.create(
            user=request.user,
            name=request.POST['name'],
            school=school
        )
        request.user.is_info_set = True
        request.user.user_name = request.POST['name']
        request.user.save()

        return redirect('student:dash')
    else:
        school_list = School.objects.all()
        context = {'school_list': school_list}
        return render(request, 'student/student_signup_info.html', context)


def dash(request):
    student = Student.objects.get(user=request.user)
    enroll_class_num = Enroll.objects.filter(student=student).filter(is_assigned=True).count()
    context = {'enroll_class_num': enroll_class_num}
    return render(request, 'student/student_dash.html', context)


def class_select(request):
    school = Student.objects.get(user=request.user).school
    class_list = Class.objects.filter(school=school)
    context = {'class_list': class_list}
    return render(request, 'student/student_class_select.html', context)


def class_signup(request, class_id):
    class_class = Class.objects.get(id=class_id)
    teacher = class_class.teacher
    student = Student.objects.get(user=request.user)
    try:
        _id = Enroll.objects.filter(class_class=class_class).get(student=student)
    except:
        _id = None
    if _id is None:
        new_enroll = Enroll.objects.create(
            class_class=class_class,
            teacher=teacher,
            student=student
        )
        return redirect('student:dash')
    else:
        return redirect('student:dash')


def my_class(request):
    student = Student.objects.get(user=request.user)
    enroll_list = Enroll.objects.filter(student=student).filter(is_assigned=True)

    for enroll in enroll_list:
        flag = 0
        lecture_pass_list = LecturePass.objects.filter(enroll=enroll)
        final_quiz_pass_list = FinalQuizPass.objects.filter(enroll=enroll)
        for lecture_pass in lecture_pass_list:
            if not lecture_pass.is_passed:
                flag = 1
                break
        for final_quiz_pass in final_quiz_pass_list:
            if not final_quiz_pass.is_passed:
                flag = 1
                break
        if flag == 0:
            enroll.is_graduated = True
            enroll.save()

    context = {'enroll_list': enroll_list}
    return render(request, 'student/student_my_class.html', context)


def take_class(request, course_id, enroll_id):
    course = Course.objects.get(id=course_id)
    enroll = Enroll.objects.get(id=enroll_id)
    lecture_list = course.lecture_set.all()
    final_quiz_list = course.finalquiz_set.all()
    lecture_pass_list = LecturePass.objects.filter(enroll=enroll)
    final_quiz_pass_list = FinalQuizPass.objects.filter(enroll=enroll)
    student = Student.objects.get(user=request.user)
    enroll_list = Enroll.objects.filter(student=student).filter(is_assigned=True)

    for enroll in enroll_list:
        flag = 0
        lecture_pass_list = LecturePass.objects.filter(enroll=enroll)
        final_quiz_pass_list = FinalQuizPass.objects.filter(enroll=enroll)
        for lecture_pass in lecture_pass_list:
            if not lecture_pass.is_passed:
                flag = 1
                break
        for final_quiz_pass in final_quiz_pass_list:
            if not final_quiz_pass.is_passed:
                flag = 1
                break
        if flag == 0:
            enroll.is_graduated = True
            enroll.save()

    context = {
        'lecture_list': lecture_list,
        'final_quiz_list': final_quiz_list,
        'course': course,
        'enroll': enroll,
        'lecture_pass_list': lecture_pass_list,
        'final_quiz_pass_list': final_quiz_pass_list
    }
    return render(request, 'student/student_take_class.html', context)


def take_lecture(request, lecture_id, enroll_id):
    lecture = Lecture.objects.get(id=lecture_id)
    enroll = Enroll.objects.get(id=enroll_id)
    context = {'lecture': lecture, 'enroll': enroll}
    return render(request, 'student/student_take_lecture.html', context)


def take_lecture_code(request, lecture_id, enroll_id):
    lecture = Lecture.objects.get(id=lecture_id)
    enroll = Enroll.objects.get(id=enroll_id)
    context = {'lecture': lecture, 'enroll': enroll}
    return render(request, 'student/student_take_lecture_code.html', context)


def take_quiz(request, quiz_id, enroll_id):
    quiz = Quiz.objects.get(id=quiz_id)
    enroll = Enroll.objects.get(id=enroll_id)
    lecture = quiz.lecture
    course = lecture.course
    lecture_pass = LecturePass.objects.filter(enroll=enroll).get(lecture=lecture)
    question_list = Question.objects.filter(quiz=quiz)
    option_list = []
    for question in question_list:
        temp = Option.objects.filter(question=question)
        option_list.append(temp)

    if request.method == 'POST':
        answer_list = request.POST.getlist('answers[]')
        pass_score = quiz.pass_score / 100
        total = 0
        correct = 0
        for question in question_list:
            total += 1
            flag = 0
            option_set = question.option_set.all()
            for option in option_set:
                if option.is_answer:
                    for answer in answer_list:
                        answer_option = Option.objects.get(id=answer)
                        if answer_option == option:
                            break
                    else:
                        flag = 1
                else:
                    for answer in answer_list:
                        answer_option = Option.objects.get(id=answer)
                        if answer_option == option:
                            flag = 1
                            break
                if flag:
                    break
            if flag == 0:
                correct += 1

        if correct/total > pass_score:
            lecture_pass.is_passed = True
            lecture_pass.score = correct/total * 100
            lecture_pass.save()
            return redirect('student:take_class', course.id, enroll.id)
        else:
            return redirect('student:take_class', course.id, enroll.id)

    else:
        context = {'quiz': quiz, 'course': course, 'question_list': question_list, 'option_list': option_list}
        return render(request, 'student/student_take_quiz.html', context)


def take_final_quiz(request, final_quiz_id, enroll_id):
    final_quiz = FinalQuiz.objects.get(id=final_quiz_id)
    enroll = Enroll.objects.get(id=enroll_id)
    course = final_quiz.course
    final_quiz_pass = FinalQuizPass.objects.filter(enroll=enroll).get(final_quiz=final_quiz)
    final_question_list = FinalQuestion.objects.filter(final_quiz=final_quiz)
    final_option_list = []
    for final_question in final_question_list:
        temp = FinalOption.objects.filter(final_question=final_question)
        final_option_list.append(temp)

    if request.method == 'POST':
        answer_list = request.POST.getlist('answers[]')
        pass_score = final_quiz.pass_score / 100
        total = 0
        correct = 0
        for final_question in final_question_list:
            total += 1
            flag = 0
            option_set = final_question.finaloption_set.all()
            for option in option_set:
                if option.is_answer:
                    for answer in answer_list:
                        answer_option = FinalOption.objects.get(id=answer)
                        if answer_option == option:
                            break
                    else:
                        flag = 1
                else:
                    for answer in answer_list:
                        answer_option = FinalOption.objects.get(id=answer)
                        if answer_option == option:
                            flag = 1
                            break
                if flag:
                    break
            if flag == 0:
                correct += 1

        if correct/total > pass_score:
            final_quiz_pass.is_passed = True
            final_quiz_pass.score = correct/total * 100
            final_quiz_pass.save()
            return redirect('student:take_class', course.id, enroll.id)
        else:
            return redirect('student:take_class', course.id, enroll.id)

    else:
        context = {
            'final_quiz': final_quiz,
            'course': course,
            'final_question_list': final_question_list,
            'final_option_list': final_option_list
        }
        return render(request, 'student/student_take_final_quiz.html', context)


def my_quiz(request):
    student = Student.objects.get(user=request.user)
    enroll_list = Enroll.objects.filter(student=student).filter(is_assigned=True)
    course_list = []
    lecture_pass_list = []
    final_quiz_pass_list = []

    for enroll in enroll_list:
        course_list.append(enroll.class_class.course)
        temp_list = LecturePass.objects.filter(enroll=enroll)
        temp_list_2 = FinalQuizPass.objects.filter(enroll=enroll)
        for temp in temp_list:
            lecture_pass_list.append(temp)
        for temp2 in temp_list_2:
            final_quiz_pass_list.append(temp2)

    total_lecture_list = []
    total_final_quiz_list = []
    for course in course_list:
        lecture_list = Lecture.objects.filter(course=course)
        total_lecture_list.append(lecture_list)
        final_quiz_list = course.finalquiz_set.all()
        total_final_quiz_list.append(final_quiz_list)

LMS/templates/student/student_class_select.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Student</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javscript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                    <ul class="gnb admin_gnb">
                            <li>
                                   <a href="{% url 'student:dash' %}">Dashboard</a>
                            </li>
                            <li class="on">
                                <a href="{% url 'student:class_select' %}">Class Room</a>
                                <ul class="depth2">
                                    <li class="on"><a href="{% url 'student:class_select' %}">Class List</a></li>
                                    <li><a href="{% url 'student:my_class' %}">My Class</a></li>
                                </ul>
                            </li>
                            <li>
                                   <a href="{% url 'student:my_quiz' %}">Quiz</a>
                            </li>
                            <li>
                                   <a href="{% url 'student:setting_profile' %}">Settings</a>
                            </li>
                    </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
              <section class="page_admin">
                     <div class="top_wrap">
                            <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
                     </div>
                     <h2 class="tit">Select class to sign up</h2>
                     <div class="con admin_con6">
                         <div class="scroll_box">
                             <div class="tbl_wrap1">
                                 <table>
                                     <colgroup>
                                         <col style="width: 15%;">
                                         <col style="width: 40%;">
                                         <col style="width: 20%;">
                                         <col style="width: auto;">
                                     </colgroup>
                                     <thead>
                                     <tr>
                                         <th>No.</th>
                                         <th>Class name</th>
                                         <th>Teacher</th>
                                         <th>Sign up</th>
                                     </tr>
                                     </thead>
                                     <tbody>
                                     {% for class in class_list %}
                                     <tr>
                                         <td>{{ forloop.counter }}</td>
                                         <td>{{ class.class_name }}</td>
                                         <td>{{ class.teacher.name }}</td>
                                         <td><a href="{% url 'student:class_signup' class.id %}">click to sign up</a></td>
                                     </tr>
                                     {% endfor %}
                                     </tbody>
                                 </table>
                             </div>
                         </div>
                     </div>
              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>

LMS/templates/student/student_setting_account.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Admin</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javascript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                     <ul class="gnb">
                            <li>
                                   <a href="{% url 'student:dash' %}">Dashboard</a>
                            </li>
                            <li>
                                   <a href="{% url 'student:class_select' %}">Class Room</a>
                            </li>
                            <li>
                                   <a href="{% url 'student:my_quiz' %}">Quiz</a>
                            </li>
                            <li class="on">
                                   <a href="{% url 'student:setting_profile' %}">Settings</a>
                                   <ul class="depth2">
                                          <li><a href="{% url 'student:setting_profile' %}">Profile</a></li>
                                          <li><a href="{% url 'student:setting_photo' %}">Photo</a></li>
                                          <li class="on"><a href="{% url 'student:setting_account' %}">Account</a></li>
                                   </ul>
                            </li>
                     </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
              <section class="page_admin">
                     <div class="top_wrap">
                            <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
                     </div>
                     <h2 class="tit">Account</h2>
                     <div class="con admin_con1">
                            <h3>Basic Information</h3>
                            <form method="POST">
                                   {% csrf_token %}
                                   <fieldset>
                                          <div class="form_con1">
                                                 <div class="box">
                                                        <h5>E-mail</h5>
                                                        <span>
                                                               <div class="input_box">
                                                                      <input type="text" placeholder="E-mail" name="email" value="{{ user.email }}">
                                                               </div>
                                                        </span>
                                                 </div>
                                                 <div class="box">
                                                        <h5>Password</h5>
                                                        <span>
                                                               <div class="input_box">
                                                                      <input class="login_input" placeholder="current password" name="current_password" type="password">
                                                               </div>
                                                        </span>
                                                        <span>
                                                               <div class="input_box">
                                                                      <input class="login_input" placeholder="new password" name="password1" type="password">
                                                               </div>
                                                        </span>
                                                        <span>
                                                               <div class="input_box">
                                                                      <input class="login_input" placeholder="retype new password" name="password2" type="password">
                                                               </div>
                                                        </span>
                                                 </div>
                                          </div>
                                   </fieldset>
                                   <div class="btn_wrap">
                                          <input type="submit" class="btn_type1" value="SAVE" style='cursor:pointer;'>
                                   </div>
                            </form>
                     </div>

              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>

LMS/templates/student/student_take_class.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Student</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}">
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javscript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                    <ul class="gnb admin_gnb">
                            <li>
                                   <a href="{% url 'student:dash' %}">Dashboard</a>
                            </li>
                            <li class="on">
                                <a href="{% url 'student:class_select' %}">Class Room</a>
                                <ul class="depth2">
                                    <li><a href="{% url 'student:class_select' %}">Class List</a></li>
                                    <li class="on"><a href="{% url 'student:my_class' %}">My Class</a></li>
                                </ul>
                            </li>
                            <li>
                                   <a href="{% url 'student:my_quiz' %}">Quiz</a>
                            </li>
                            <li>
                                   <a href="{% url 'student:setting_profile' %}">Settings</a>
                            </li>
                    </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
              <section class="page_admin">
                     <div class="top_wrap">
                            <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
                     </div>
                     <h2 class="tit">Take Class</h2>
                     <div class="con upload_con">
                   {% if not lecture_list and not final_quiz_list%}
                   There is no lecture or quiz uploaded yet
                   {% else %}
                   {% if lecture_list %}
                   {% for lecture in lecture_list %}
                   <ul class="inner_box">
                       <li>
                           <div class="top_box">
                               <p><a href="{% url 'student:take_lecture' lecture.id enroll.id %}">class {{ forloop.counter }}</a></p>
                               {% for lecture_pass in lecture_pass_list %}
                                    {% if lecture_pass.lecture == lecture %}
                                        {% if lecture_pass.is_passed %}
                                        <font color="blue">Pass</font>
                                        {% else %}
                                        <font color="red">Fail</font>
                                        {% endif %}
                                    {% endif %}
                               {% endfor %}
                           </div>
                       </li>
                   </ul>
                   {% endfor %}
                   {% endif %}
                   {% if final_quiz_list %}
                   {% for final_quiz in final_quiz_list %}
                   <ul class="inner_box">
                       <li class="final_quiz_box">
                           <div class="top_box bottom_none">
                               <p><a href="{% url 'student:take_final_quiz' final_quiz.id enroll.id %}">final quiz {{ forloop.counter }}</a></p>
                               {% for final_quiz_pass in final_quiz_pass_list %}
                                    {% if final_quiz_pass.final_quiz == final_quiz %}
                                        {% if final_quiz_pass.is_passed %}
                                        <font color="blue">Pass</font>
                                        {% else %}
                                        <font color="red">Fail</font>
                                        {% endif %}
                                    {% endif %}
                               {% endfor %}
                           </div>
                       </li>
                   </ul>
                   {% endfor %}
                   {% endif %}
                   {% endif %}
                         <button type="button" class="btn_type1" onclick="location.href='{% url 'student:my_class'%}'">Done</button>
               </div>
              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>