LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('superadmin/', include('superadmin.urls')),
    path('school/', include('school.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('accounts/', include('account.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
]

LMS/school/urls.py
from django.urls import path

from . import views

app_name = 'school'

urlpatterns = [
    path('signup_info/', views.signup_info, name='signup_info'),
    path('dash/', views.dash, name='dash'),
    path('my_course/', views.my_course, name='my_course'),
    path('course_select/', views.course_select, name='course_select'),
    path('copy_course/<int:course_id>/', views.copy_course, name='copy_course'),
    path('course_modify/<int:course_id>/', views.course_modify, name='course_modify'),
    path('lecture_modify/<int:lecture_id>/', views.lecture_modify, name='lecture_modify'),
    path('quiz_modify/<int:quiz_id>/', views.quiz_modify, name='quiz_modify'),
    path('final_quiz_modify/<int:final_quiz_id>/', views.final_quiz_modify, name='final_quiz_modify'),
    path('lecture_quiz_upload/<int:course_id>/', views.lecture_quiz_upload, name='lecture_quiz_upload'),
    path('add_lecture/<int:course_id>/', views.add_lecture, name='add_lecture'),
    path('add_quiz/<int:lecture_id>/', views.add_quiz, name='add_quiz'),
    path('add_final_quiz/<int:course_id>/', views.add_final_quiz, name='add_final_quiz'),
    path('teacher_list/', views.teacher_list, name='teacher_list'),
    path('student_list/', views.student_list, name='student_list'),
    path('quiz_list/', views.quiz_list, name='quiz_list'),
    path('setting_profile/', views.setting_profile, name='setting_profile'),
    path('setting_photo/', views.setting_photo, name='setting_photo'),
    path('setting_account/', views.setting_account, name='setting_account'),
]

LMS/school/models.py
from django.db import models
from account.models import User


class School(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False)
    CP = models.CharField(max_length=50, null=False)
    CPD = models.CharField(max_length=50, null=False)
    address = models.CharField(max_length=50, null=False)
    mobile = models.CharField(max_length=50, null=False)
    phone = models.CharField(max_length=50, null=False)
    SCP = models.CharField(max_length=50, null=True)
    SCPMN = models.CharField(max_length=50, null=True)
    SCPD = models.CharField(max_length=50, null=True)
    email = models.CharField(max_length=50, null=True)
    reference = models.CharField(max_length=50, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

LMS/school/views.py
from django.shortcuts import render, redirect
from .models import *
from teacher.models import *
from student.models import *
from superadmin.models import *
from account.forms import UserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.hashers import check_password


def signup_info(request):
    if request.method == 'POST':
        new_school = School.objects.create(
            user=request.user,
            name=request.POST['name'],
            CP=request.POST['CP'],
            CPD=request.POST['CPD'],
            address=request.POST['address'],
            mobile=request.POST['mobile'],
            phone=request.POST['phone'],
            SCP=request.POST['SCP'],
            SCPMN=request.POST['SCPMN'],
            SCPD=request.POST['SCPD'],
            email=request.POST['email'],
            reference=request.POST['reference']
        )
        request.user.is_info_set = True
        request.user.user_name = request.POST['name']
        request.user.save()

        return redirect('/')
    else:
        return render(request, 'school/school_signup_info.html')


def dash(request):
    school = School.objects.get(user=request.user)
    student_list = Student.objects.filter(school=school)
    students = student_list.count()
    teacher_list = Teacher.objects.filter(school=school)
    teachers = teacher_list.count()
    course_list = list(Course.objects.filter(author=request.user))

    for teacher in teacher_list:
        temp_list = Course.objects.filter(author=teacher.user)
        for temp in temp_list:
            course_list.append(temp)
    courses = len(course_list)
    lecture_list = []
    quiz_list = []
    final_quiz_list = []
    for course in course_list:
        temp_list = Lecture.objects.filter(course=course)
        temp_list_2 = FinalQuiz.objects.filter(course=course)
        for temp in temp_list:
            lecture_list.append(temp)
            quiz_list.append(temp.quiz)
        for temp2 in temp_list_2:
            final_quiz_list.append(temp2)
    lectures = len(lecture_list)
    quizzes = len(quiz_list) + len(final_quiz_list)

    enroll_list = []
    graduate_enroll = 0
    for student in student_list:
        temp_list = Enroll.objects.filter(student=student).filter(is_assigned=True)
        graduate_enroll += Enroll.objects.filter(student=student).filter(is_assigned=True).filter(is_graduated=True).count()
        for temp in temp_list:
            enroll_list.append(temp)

    total_enroll = len(enroll_list)
    try:
        graduate_rate = graduate_enroll/total_enroll * 100
    except:
        graduate_rate = 0

    context = {
        'students': students,
        'teachers': teachers,
        'courses': courses,
        'graduate_rate': graduate_rate,
        'lectures': lectures,
        'quizzes': quizzes
    }
    return render(request, 'school/school_dash.html', context)


def my_course(request):
    school = School.objects.get(user=request.user)
    teacher_list = Teacher.objects.filter(school=school)
    teachers = teacher_list.count()
    course_list = list(Course.objects.filter(author=request.user))

    for teacher in teacher_list:
        temp_list = Course.objects.filter(author=teacher.user)
        for temp in temp_list:
            course_list.append(temp)
    context = {'course_list': course_list}
    return render(request, 'school/school_my_course.html', context)


def course_select(request):
    course_list = Course.objects.filter(depth=1)
    context = {'course_list': course_list}
    return render(request, 'school/school_course_select.html', context)


def copy_course(request, course_id):
    course = Course.objects.get(id=course_id)
    lecture_list = Lecture.objects.filter(course=course)
    final_quiz_list = FinalQuiz.objects.filter(course=course)
    course.pk = None # how to copy object
    course.author = request.user
    course.depth = 2
    course.save()

    for lecture in lecture_list:
        quiz = lecture.quiz
        question_list = Question.objects.filter(quiz=quiz)
        lecture.pk = None
        quiz.pk = None
        quiz.save()

        for question in question_list:
            option_list = Option.objects.filter(question=question)
            question.pk = None
            question.quiz = quiz
            question.save()
            for option in option_list:
                option.pk = None
                option.question = question
                option.save()

        lecture.course = course
        lecture.quiz = quiz
        lecture.save()

    for final_quiz in final_quiz_list:
        final_question_list = FinalQuestion.objects.filter(final_quiz=final_quiz)
        final_quiz.pk = None
        final_quiz.course = course
        final_quiz.save()

        for final_question in final_question_list:
            final_option_list = FinalOption.objects.filter(final_question=final_question)
            final_question.pk = None
            final_question.final_quiz = final_quiz
            final_question.save()

            for final_option in final_option_list:
                final_option.pk = None
                final_option.final_question = final_question
                final_option.save()

    return redirect('school:my_course')


def course_modify(request, course_id):
    course = Course.objects.get(id=course_id)

    if course.author != request.user:
        return redirect('/')
    if request.method == "POST":
        level = request.POST.get("level", None)
        category = request.POST.get("category", None)
        difficulty = request.POST.get("difficulty", None)
        course.title = request.POST['title']
        course.description = request.POST['description']
        course.price = request.POST['price']
        course.level = level
        course.category = category
        course.difficulty = difficulty
        course.tag = request.POST.get('tag_radio')
        course.type = request.POST.get('type_radio')
        course.save()

        return redirect('school:lecture_quiz_upload', course.id)
    else:
        context = {'course': course}
        return render(request, 'school/school_course_modify.html', context)


def lecture_quiz_upload(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.author != request.user:
        print('here')
        return redirect('/')

    lecture_list = course.lecture_set.all()
    final_quiz_list = course.finalquiz_set.all()
    context = {'lecture_list': lecture_list, 'final_quiz_list': final_quiz_list, 'course': course}
    return render(request, 'school/school_lecture_quiz_upload.html', context)


def add_lecture(request, course_id):
    course = Course.objects.get(id=course_id)

    if request.method == "POST":
        new_quiz = Quiz.objects.create(title='temp')
        new_lecture = Lecture.objects.create(
            course=course,
            quiz=new_quiz,
            title=request.POST['title'],
            video_link=request.POST['video_link'],
            code=request.POST['code'],
            file=request.FILES.get('file')
        )
        return redirect('school:add_quiz', new_lecture.id)
    else:
        return render(request, 'school/school_add_lecture.html')


def add_quiz(request, lecture_id):
    lecture = Lecture.objects.get(id=lecture_id)
    course = Course.objects.get(id=lecture.course.id)
    quiz = Quiz.objects.get(id=lecture.quiz.id)

    if request.method == "POST":
        quiz.title = request.POST['title']

        new_question = Question.objects.create(
            quiz=quiz,
            content=request.POST['content'],
            image=request.FILES.get('image1')
        )
        try:
            a = request.POST['correct1']
            bool1 = True
        except:
            bool1 = False
        new_option_1 = Option.objects.create(
            question=new_question,
            content=request.POST['option_content_1'],
            image=request.FILES.get('image2'),
            is_answer=bool1
        )

        try:
            a = request.POST['correct2']
            bool2 = True
        except:
            bool2 = False
        new_option_2 = Option.objects.create(
            question=new_question,
            content=request.POST['option_content_2'],
            image=request.FILES.get('image3'),
            is_answer=bool2
        )

        try:
            a = request.POST['correct3']
            bool3 = True
        except:
            bool3 = False
        new_option_3 = Option.objects.create(
            question=new_question,
            content=request.POST['option_content_3'],
            image=request.FILES.get('image4'),
            is_answer=bool3
        )
        if request.POST['score'] == '60':
            score = 60
        elif request.POST['score'] == '70':
            score = 70
        else:
            score = 80
        quiz.pass_score = score
        quiz.save()
        return redirect('school:lecture_quiz_upload', course.id)
    else:
        return render(request, 'school/school_add_quiz.html')


def add_final_quiz(request, course_id):
    course = Course.objects.get(id=course_id)

    if request.method == "POST":
        new_final_quiz = FinalQuiz.objects.create(
            course=course,
            title=request.POST['title']
        )
        new_final_question = FinalQuestion.objects.create(
            final_quiz=new_final_quiz,
            content=request.POST['content'],
            image=request.FILES.get('image1')
        )
        try:
            a = request.POST['correct1']
            bool1 = True
        except:
            bool1 = False
        new_final_option_1 = FinalOption.objects.create(
            final_question=new_final_question,
            content=request.POST['option_content_1'],
            image=request.FILES.get('image2'),
            is_answer=bool1
        )

        try:
            a = request.POST['correct2']
            bool2 = True
        except:
            bool2 = False

LMS/templates/school/school_lecture_quiz_upload.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Admin</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javscript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                    <ul class="gnb admin_gnb">
                        <li>
                            <a href="{% url 'school:dash' %}">Dashboard</a>
                        </li>
                        <li class="on">
                            <a href="{% url 'school:my_course' %}">Course</a>
                            <ul class="depth2">
                                <li class="on"><a href="{% url 'school:my_course' %}">Course List</a></li>
                                <li><a href="{% url 'school:course_select' %}">Upload</a></li>
                            </ul>
                        </li>
                            <li>
                                   <a href="{% url 'school:teacher_list' %}">Teacher</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:student_list' %}">Student</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:quiz_list' %}">Quiz</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:setting_profile' %}">Settings</a>
                            </li>
                    </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
           <section class="page_admin">
               <div class="top_wrap">
                   <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
               </div>
               <h2 class="tit">Upload</h2>
               <div class="con upload_con">
                   <div class="tx_r bm30">
                       <a href="{% url 'school:add_lecture' course.id %}" class="btn_add2">ADD Lecture & Quiz</a>
                       <a href="{% url 'school:add_final_quiz' course.id %}" class="btn_add2">ADD Final Quiz</a>
                   </div>
                   {% if not lecture_list and not final_quiz_list%}
                   There is no lecture or quiz uploaded yet<br><br>
                   {% else %}
                   {% if lecture_list %}
                   {% for lecture in lecture_list %}
                   <ul class="inner_box">
                       <li>
                           <div class="top_box">
                               <p><a href="{% url 'school:lecture_modify' lecture.id %}">{{ lecture.title }}</a></p>
                           </div>
                       </li>
                       <li class="quiz_box">
                           <div class="top_box bottom_none">
                               <p><a href="{% url 'school:quiz_modify' lecture.quiz.id %}">{{ lecture.quiz.title }}</a></p>
                           </div>
                       </li>
                   </ul>
                   {% endfor %}
                   {% endif %}
                   {% if final_quiz_list %}
                   {% for final_quiz in final_quiz_list %}
                   <ul class="inner_box">
                       <li class="final_quiz_box">
                           <div class="top_box bottom_none">
                               <p><a href="{% url 'school:final_quiz_modify' final_quiz.id %}">{{ final_quiz.title }}</a></p>
                           </div>
                       </li>
                   </ul>
                   {% endfor %}
                   {% endif %}
                   {% endif %}
                   <a href="{% url 'school:my_course'%}" class="btn_type1">Done</a>
               </div>
              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>

LMS/templates/school/school_my_course.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Admin</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javscript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                    <ul class="gnb admin_gnb">
                        <li>
                            <a href="{% url 'school:dash' %}">Dashboard</a>
                        </li>
                        <li class="on">
                            <a href="{% url 'school:my_course' %}">Course</a>
                            <ul class="depth2">
                                <li class="on"><a href="{% url 'school:my_course' %}">Course List</a></li>
                                <li><a href="{% url 'school:course_select' %}">Upload</a></li>
                            </ul>
                        </li>
                            <li>
                                   <a href="{% url 'school:teacher_list' %}">Teacher</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:student_list' %}">Student</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:quiz_list' %}">Quiz</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:setting_profile' %}">Settings</a>
                            </li>
                    </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
              <section class="page_admin">
                     <div class="top_wrap">
                            <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
                     </div>
                     <h2 class="tit">Course List</h2>
                     <div class="con admin_con6">
                         <div class="scroll_box">
                             <div class="tbl_wrap1">
                                 <table>
                                     <colgroup>
                                         <col style="width: 15%;">
                                         <col style="width: 40%;">
                                         <col style="width: 20%;">
                                         <col style="width: auto;">
                                     </colgroup>
                                     <thead>
                                     <tr>
                                         <th>No.</th>
                                         <th>Course Title</th>
                                         <th>Author</th>
                                         <th>Modify</th>
                                     </tr>
                                     </thead>
                                     <tbody>
                                     {% for course in course_list %}
                                     <tr>
                                         <td>{{ forloop.counter }}</td>
                                         <td>{{ course.title }}</td>
                                         <td>{{ course.author.user_name }}</td>
                                         {% if course.author == user %}
                                         <td><a href="{% url 'school:course_modify' course.id %}">click to modify</a></td>
                                         {% else %}
                                         <td></td>
                                         {% endif %}
                                     </tr>
                                     {% endfor %}
                                     </tbody>
                                 </table>
                             </div>
                         </div>
                     </div>
              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>

LMS/templates/school/school_setting_photo.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=1600">
<title>Admin</title>
<meta name="description" content="Admin">
<meta property="og:type" content="website">
<meta property="og:title" content="Admin">
<meta property="og:description" content="Admin">
<meta property="og:image" content="">
<meta property="og:url" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css">
<link rel="stylesheet" href="{% static 'css/default.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body class="body">
<div id="wrap" class="">
       <!-- skipNav -->
       <div class="skipnavi">
              <a href="#header">header</a>
              <a href="#container">container</a>
              <a href="#footer">footer</a>
       </div>
       <!-- header -->
       <header class="header_admin" id="header">
              <div class="top_header">
                     <!-- 무슨기능을 하는지 모름 -->
                     <a href="javascript: void(0)" class="btn_m">menu button</a>
                     <!-- //무슨기능을 하는지 모름 -->
                     <div class="profile_wrap">
                            <div class="img">
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                            </div>
                     </div>
                     <strong>{{ user.user_name }}</strong>
              </div>
              <nav>
                     <ul class="gnb">
                        <li>
                            <a href="{% url 'school:dash' %}">Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'school:my_course' %}">Course</a>
                        </li>
                            <li>
                                   <a href="{% url 'school:teacher_list' %}">Teacher</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:student_list' %}">Student</a>
                            </li>
                            <li>
                                   <a href="{% url 'school:quiz_list' %}">Quiz</a>
                            </li>
                            <li class="on">
                                   <a href="{% url 'school:setting_profile' %}">Settings</a>
                                   <ul class="depth2">
                                          <li><a href="{% url 'school:setting_profile' %}">Profile</a></li>
                                          <li class="on"><a href="{% url 'school:setting_photo' %}">Photo</a></li>
                                          <li><a href="{% url 'school:setting_account' %}">Account</a></li>
                                   </ul>
                            </li>
                     </ul>
              </nav>
       </header>
       <!-- //header -->
       <!-- main -->
       <main class="container" id="container">
              <section class="page_admin">
                     <div class="top_wrap">
                            <a href="{% url 'account:logout' %}" class="btn_logout">Log out</a>
                     </div>
                     <h2 class="tit">School Logo</h2>
                     <div class="con admin_con1">
                            <form method="POST" enctype="multipart/form-data">
                                   {% csrf_token %}
                                   <h3>Image</h3><br><br>
                                   {% if user.image %}
                                          <img src = "{{ user.image.url }}"><br>
                                   {% endif %}
                                   <h3>Add / Change Image:</h3><br>
                                   <input type="file" name="image">
                                   <div class="btn_wrap">
                                          <input type="submit" class="btn_type1" value="SAVE" style='cursor:pointer;'>
                                   </div>
                            </form>
                     </div>

              </section>
       </main>
       <!-- main -->
</div>
</body>
</html>