LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('superadmin/', include('superadmin.urls')),
    path('school/', include('school.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('accounts/', include('account.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
]

LMS/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>LMS</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

LMS/templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

LMS/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Homepage</h1>
{% if user.is_authenticated %}
    <a href="{% url 'account:logout' %}" class="btn btn-primary">로그아웃</a>
    <a href="{% url 'account:detail' %}" class="btn btn-primary">내 정보</a>
{% else %}
    <a href="{% url 'account:signup' %}" class="btn btn-primary">회원가입</a>
    <a href="{% url 'account:login' %}" class="btn btn-primary">로그인</a>
{% endif %}
{% endblock %}